static const ChkItem CK_C0[] = { // Kokiri Forest & Deku Tree
    { "c0_swkokiri", "Kokiri Sword",    "Thru the tunnel behind the training area.", "Kokiri Forest - training ground, past the fences.", CKI_SPRITE, 0x3B, CK_EQUIP, 0x0587A0E, 0x01 },
    { "c0_shdeku",   "Deku Shield",     "Buy it at the shop with the red roof (40 rupees).", "Kokiri Forest shop.", CKI_SPRITE, 0x3E, CK_EQUIP, 0x0587A0E, 0x10 },
    { "c0_stick",    "Deku Stick",      "Picked up in Kokiri Forest.", "Kokiri Forest.", CKI_SPRITE, 0x00, CK_INVSLOT, 0x5879E4, 0 },
    { "c0_nut",      "Deku Nut",        "Found inside the Great Deku Tree.", "Great Deku Tree - early room.", CKI_SPRITE, 0x01, CK_INVSLOT, 0x5879E5, 0 },
    { "c0_map",      "Dungeon Map",     "Great Deku Tree.", "Great Deku Tree.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A18, 0x04 },
    { "c0_sling",    "Fairy Slingshot", "Great Deku Tree, main room.", "Great Deku Tree.", CKI_SPRITE, 0x06, CK_INVSLOT, 0x5879EA, 0 },
    { "c0_compass",  "Compass",         "Great Deku Tree.", "Great Deku Tree.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A18, 0x02 },
    { "c0_gs1",      "Gold Skulltula 1", "In the compass room.", "Great Deku Tree - compass room.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c0_gs2",      "Gold Skulltula 2", "Lower level, on the vines.", "Great Deku Tree - lower level.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c0_gs3",      "Gold Skulltula 3", "Lower level, on the grates.", "Great Deku Tree - lower level.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c0_hc1",      "Heart Container", "Defeat Queen Gohma.", "Great Deku Tree - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A16, 0x04 },
    { "c0_ocarina",  "Fairy Ocarina",   "Talk to Saria on your way out of the forest.", "Kokiri Forest exit.", CKI_SPRITE, 0x07, CK_INVSLOT, 0x5879EB, 0 },
};
static const ChkItem CK_C1[] = { // Hyrule Castle & Kakariko Village
    { "c1_gs1",      "Gold Skulltula 1", "In a crate in the guardhouse.", "Hyrule Castle Market - guardhouse.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c1_gs2",      "Gold Skulltula 2", "First tree in the area.", "Hyrule Castle grounds.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c1_letter",   "Zelda's Letter",  "Get caught sneaking into the castle, then talk to Malon.", "Hyrule Castle grounds.", CKI_SPRITE, 0x23, CK_MANUAL, 0, 0 },
    { "c1_song1",    "Song: Zelda's Lullaby", "Impa teaches it before Kakariko.", "Hyrule Castle grounds.", CKI_NOTE, 0, CK_EQUIP, 0x0587A15, 0x10 },
    { "c1_song2",    "Song: Sun's Song",      "Learn it inside the Royal Tomb.", "Kakariko Graveyard.", CKI_NOTE, 0, CK_EQUIP, 0x0587A15, 0x80 },
    { "c1_hp1",      "Heart Piece 1",   "Inside the 4th grave from the right, near the Royal Tomb.", "Kakariko Graveyard.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c1_shhyl",    "Hylian Shield",   "Inside a grave in the front row (three flowers in front).", "Kakariko Graveyard.", CKI_SPRITE, 0x3F, CK_EQUIP, 0x0587A0E, 0x20 },
    { "c1_bottle1",  "Bottle #1",       "Win Talon's cow-catching minigame (10 rupees).", "Lon Lon Ranch.", CKI_SPRITE, 0x14, CK_INVSLOT, 0x5879F6, 0 },
    { "c1_gs3",      "Gold Skulltula 3", "Tree behind the farm buildings.", "Lon Lon Ranch.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c1_song3",    "Song: Epona's Song", "Play your Ocarina for Malon.", "Lon Lon Ranch.", CKI_NOTE, 0, CK_EQUIP, 0x0587A15, 0x20 },
    { "c1_gs4",      "Gold Skulltula 4", "Behind the feeding trough, at night.", "Lon Lon Ranch (night).", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c1_hp2",      "Heart Piece 2",   "Inside the silo, through the tunnel behind the crates.", "Lon Lon Ranch.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c1_gs5",      "Gold Skulltula 5", "Back of the Know-It-All Brothers' house, at night.", "Kokiri Forest (night).", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c1_seedbag",  "Deku Seed Bullet Bag", "Shoot the target 3 times (score 100 each).", "Lost Woods entrance.", CKI_SPRITE, 0x101, CK_UPGRADE, 0x0587A10, (14 << 3) | 1 },
    { "c1_hp3",      "Heart Piece 3",   "Play the follow-along minigame with your Ocarina.", "Lost Woods.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c1_song4",    "Song: Saria's Song", "Talk to Saria after navigating the Lost Woods.", "Sacred Forest Meadow.", CKI_NOTE, 0, CK_EQUIP, 0x0587A15, 0x40 },
};
static const ChkItem CK_C2[] = { // Zora's Domain & Jabu-Jabu's Belly
    { "c2_letter",   "Ruto's Letter",       "Dive to the bottom of Lake Hylia to find a bottle with a letter inside.", "Lake Hylia - lakebed.", CKI_SPRITE, 0x1B, CK_MANUAL, 0, 0 },
    { "c2_kingzora", "Pass King Zora",      "Show the letter to King Zora in his throne room; he slides aside to open the way to Zora's Fountain.", "Zora's Domain - King Zora's chamber.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c2_jabu",     "Enter Jabu-Jabu's Belly", "Catch a fish in a bottle and offer it to Lord Jabu-Jabu; he'll swallow you whole.", "Zora's Fountain.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c2_map",      "Dungeon Map",         "Jabu-Jabu's Belly.", "Jabu-Jabu's Belly.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A1A, 0x04 },
    { "c2_compass",  "Compass",             "Jabu-Jabu's Belly.", "Jabu-Jabu's Belly.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A1A, 0x02 },
    { "c2_boomerang","Boomerang",           "Found in a chest inside the dungeon; needed to stun enemies and pull switches.", "Jabu-Jabu's Belly.", CKI_SPRITE, 0x0E, CK_INVSLOT, 0x5879F0, 0 },
    { "c2_ruto",     "Rescue Princess Ruto","Find her trapped behind a switch-locked cage partway through the dungeon.", "Jabu-Jabu's Belly - Ruto's cage room.", CKI_KEYITEM, 0, CK_EQUIP, 0x0587A16, 0x10 },
    { "c2_sapphire", "Zora's Sapphire",     "Ruto hands it over once you've freed her and are heading toward the boss door.", "Jabu-Jabu's Belly.", CKI_SPRITE, 0x10C, CK_EQUIP, 0x0587A16, 0x10 },
    { "c2_gs1",      "Gold Skulltula 1",    "Stuck to the ladder at the waterfall leading up into Zora's Domain, at night.", "Zora's River - waterfall ladder.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c2_gs2",      "Gold Skulltula 2",    "Jump onto the fence by the wooden bridge and look up at the wall, at night.", "Zora's River - bridge fence.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c2_gs3",      "Gold Skulltula 3",    "Near the top of the frozen waterfall past King Zora's chamber, at night.", "Zora's Domain.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c2_heart",    "Heart Piece",         "Step on the log jutting into the river and play the Song of Storms for the frogs.", "Zora's River - frog log.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c2_hc",       "Heart Container",     "Defeat Barinade.", "Jabu-Jabu's Belly - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A16, 0x10 },
};
static const ChkItem CK_C3[] = { // Death Mountain (Goron City & Dodongo's Cavern)
    { "c3_gorondoor","Meet Darunia",        "Play Zelda's Lullaby in front of the stone door on Goron City's bottom floor.", "Goron City.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c3_dodongo",  "Enter Dodongo's Cavern", "Roll a bomb flower into the boulder blocking the cavern entrance to blast it open.", "Death Mountain Trail - cavern entrance.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c3_map",      "Dungeon Map",         "Dodongo's Cavern.", "Dodongo's Cavern.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A19, 0x04 },
    { "c3_compass",  "Compass",             "Dodongo's Cavern.", "Dodongo's Cavern.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A19, 0x02 },
    { "c3_bombbag",  "Bomb Bag",            "Found in a chest guarded by a Lizalfos in the cavern's central room.", "Dodongo's Cavern.", CKI_SPRITE, 0x02, CK_UPGRADE, 0x0587A10, (3 << 3) | 1 },
    { "c3_gs1",      "Gold Skulltula 1",    "Bomb the cracked wall along the trail between Kakariko and the cavern entrance.", "Death Mountain Trail.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c3_gs2",      "Gold Skulltula 2",    "Near the summit, hiding behind a boulder that needs the Megaton Hammer, at night.", "Death Mountain Trail - summit path.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c3_gs3",      "Gold Skulltula 3",    "Bomb into the side room in Goron City and roll into the crate at the back.", "Goron City.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c3_heart1",   "Heart Piece 1",       "Plant a Magic Bean at the cavern entrance, then return as an adult and ride the stalk up.", "Death Mountain Trail - cavern entrance.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c3_heart2",   "Heart Piece 2",       "Backflip off the low fence near the cavern entrance.", "Death Mountain Trail.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c3_hc",       "Heart Container",     "Defeat King Dodongo.", "Dodongo's Cavern - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A16, 0x08 },
    { "c3_ruby",     "Goron's Ruby",        "Darunia gives it to you after you defeat King Dodongo.", "Dodongo's Cavern.", CKI_SPRITE, 0x118, CK_EQUIP, 0x0587A16, 0x08 },
};
static const ChkItem CK_C4[] = { // Lake Hylia & Gerudo Valley
    { "c4_gs1",      "Gold Skulltula 1",    "Drop a bug into the soft soil by the river, below the second bridge.", "Gerudo Valley.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c4_gs2",      "Gold Skulltula 2",    "Near the entrance, by the wooden bridge and mini waterfall, at night.", "Gerudo Valley.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c4_gs3",      "Gold Skulltula 3",    "On the small island far out in the lake, at night.", "Lake Hylia.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c4_gs4",      "Gold Skulltula 4",    "In a patch of dirt near the Lakeside Laboratory.", "Lake Hylia - Lakeside Laboratory.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c4_gs5",      "Gold Skulltula 5",    "Behind the Lakeside Laboratory at night; use the Boomerang to snag it.", "Lake Hylia - Lakeside Laboratory.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c4_heart1",   "Heart Piece 1",       "Bomb the center of the fenced-in grassy area near the lake's entrance to reveal a hole.", "Lake Hylia - entrance.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c4_heart2",   "Heart Piece 2",       "Plant a Magic Bean next to the Lakeside Laboratory, then return as an adult and climb the stalk.", "Lake Hylia - Lakeside Laboratory.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c4_heart3",   "Heart Piece 3",       "Grab a Cucco and float behind the big waterfall, then climb the ladder.", "Gerudo Valley - waterfall.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c4_heart4",   "Heart Piece 4",       "Float across on a Cucco to the small platform and smash the crate.", "Gerudo Valley.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c4_fishing",  "Fishing Pond",        "Rent a rod at the Fishing Pond and try landing a big catch.", "Lake Hylia - Fishing Pond.", CKI_SPRITE, 0x119, CK_MANUAL, 0, 0 },
};
static const ChkItem CK_C5[] = { // Becoming an Adult
    { "c5_present",  "Open the Door of Time","Place all three Spiritual Stones on the altar and play the Song of Time.", "Temple of Time.", CKI_KEYITEM, 0, CK_EQUIP, 0x0587A0E, 0x02 },
    { "c5_mastersword","Master Sword",      "Pull it from its pedestal beyond the Door of Time.", "Temple of Time - Sacred realm pedestal.", CKI_SPRITE, 0x3C, CK_EQUIP, 0x0587A0E, 0x02 },
    { "c5_timeskip", "Awaken as an Adult",  "Seven years pass in an instant the moment you draw the Master Sword.", "Temple of Time.", CKI_KEYITEM, 0, CK_EQUIP, 0x0587A0E, 0x02 },
    { "c5_sheik",     "Meet Sheik",         "A mysterious figure appears in the Temple of Time as you awaken.", "Temple of Time.", CKI_KEYITEM, 0, CK_EQUIP, 0x0587A0E, 0x02 },
    { "c5_prelude",  "Song: Prelude of Light", "Taught by Sheik right after you wake up as an adult.", "Temple of Time.", CKI_NOTE, 6, CK_EQUIP, 0x0587A15, 0x08 },
    { "c5_rauru",    "Rauru, Sage of Light","He awakens and grants you his medallion the moment you meet him.", "Temple of Time - Chamber of Sages.", CKI_SPRITE, 0x117, CK_EQUIP, 0x0587A14, 0x20 },
    { "c5_lightmed", "Light Medallion",     "Given automatically the moment Rauru awakens as the Sage of Light.", "Temple of Time - Chamber of Sages.", CKI_SPRITE, 0x117, CK_EQUIP, 0x0587A14, 0x20 },
};
static const ChkItem CK_C6[] = { // Forest Temple
    { "c6_minuet",   "Song: Minuet of Forest", "Taught by Sheik in the Sacred Forest Meadow, right before the temple entrance.", "Sacred Forest Meadow.", CKI_NOTE, 1, CK_EQUIP, 0x0587A14, 0x40 },
    { "c6_map",      "Dungeon Map",         "Forest Temple.", "Forest Temple.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A1B, 0x04 },
    { "c6_compass",  "Compass",             "Forest Temple.", "Forest Temple.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A1B, 0x02 },
    { "c6_bosskey",  "Boss Key",            "Forest Temple.", "Forest Temple.", CKI_SPRITE, 0x10A, CK_EQUIP, 0x0587A1B, 0x01 },
    { "c6_bow",      "Fairy Bow",           "Found in a chest after solving the eye-switch puzzle in the well room.", "Forest Temple.", CKI_SPRITE, 0x03, CK_INVSLOT, 0x5879E7, 0 },
    { "c6_gs1",      "Gold Skulltula 1",    "In the block-pushing courtyard near the entrance.", "Forest Temple - west courtyard.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c6_heart",    "Heart Piece",         "In the west courtyard, reached by pushing the two-story block up to the ledge.", "Forest Temple - west courtyard.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c6_hc",       "Heart Container",     "Defeat Phantom Ganon.", "Forest Temple - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A14, 0x01 },
    { "c6_medal",    "Forest Medallion",    "Given automatically once Phantom Ganon falls.", "Forest Temple - boss room.", CKI_SPRITE, 0x10B, CK_EQUIP, 0x0587A14, 0x01 },
};
static const ChkItem CK_C7[] = { // Fire Temple
    { "c7_bolero",   "Song: Bolero of Fire","Taught by Sheik on Death Mountain Crater, near the temple entrance.", "Death Mountain Crater.", CKI_NOTE, 2, CK_EQUIP, 0x0587A14, 0x80 },
    { "c7_map",      "Dungeon Map",         "Fire Temple.", "Fire Temple.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A1C, 0x04 },
    { "c7_compass",  "Compass",             "Fire Temple.", "Fire Temple.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A1C, 0x02 },
    { "c7_bosskey",  "Boss Key",            "Fire Temple.", "Fire Temple.", CKI_SPRITE, 0x10A, CK_EQUIP, 0x0587A1C, 0x01 },
    { "c7_hammer",   "Megaton Hammer",      "Found in a chest guarded by two Flare Dancers.", "Fire Temple.", CKI_SPRITE, 0x11, CK_INVSLOT, 0x5879F3, 0 },
    { "c7_gs1",      "Gold Skulltula 1",    "In a side room, reachable by crossing narrow ledges above the lava.", "Fire Temple.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c7_heart",    "Heart Piece",         "In a side chamber reached by smashing a switch across a lava pit with the Megaton Hammer.", "Fire Temple.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c7_hc",       "Heart Container",     "Defeat Volvagia.", "Fire Temple - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A14, 0x02 },
    { "c7_medal",    "Fire Medallion",      "Given automatically once Volvagia falls.", "Fire Temple - boss room.", CKI_SPRITE, 0x113, CK_EQUIP, 0x0587A14, 0x02 },
};
static const ChkItem CK_C8[] = { // Water Temple
    { "c8_serenade", "Song: Serenade of Water", "Taught by Sheik at Lake Hylia before you dive down to the temple entrance.", "Lake Hylia.", CKI_NOTE, 3, CK_EQUIP, 0x0587A15, 0x01 },
    { "c8_map",      "Dungeon Map",         "Water Temple.", "Water Temple.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A1D, 0x04 },
    { "c8_compass",  "Compass",             "Water Temple.", "Water Temple.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A1D, 0x02 },
    { "c8_bosskey",  "Boss Key",            "Water Temple.", "Water Temple.", CKI_SPRITE, 0x10A, CK_EQUIP, 0x0587A1D, 0x01 },
    { "c8_longshot", "Longshot",            "Found in a chest guarded by Dark Link.", "Water Temple.", CKI_SPRITE, 0x0B, CK_INVSLOT, 0x5879ED, 0x0B },
    { "c8_gs1",      "Gold Skulltula 1",    "In the room behind the central pillar, once the water level is raised.", "Water Temple.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c8_gs2",      "Gold Skulltula 2",    "In one of the side corridors reachable with Iron Boots.", "Water Temple.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c8_heart",    "Heart Piece",         "Behind a locked door, opened by hitting a switch with the Longshot at the highest water level.", "Water Temple.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c8_hc",       "Heart Container",     "Defeat Morpha.", "Water Temple - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A14, 0x04 },
    { "c8_medal",    "Water Medallion",     "Given automatically once Morpha falls.", "Water Temple - boss room.", CKI_SPRITE, 0x114, CK_EQUIP, 0x0587A14, 0x04 },
};
static const ChkItem CK_C9[] = { // Shadow Temple
    { "c9_nocturne", "Song: Nocturne of Shadow", "Taught by Sheik at the Kakariko graveyard, in front of the temple entrance.", "Kakariko Village - graveyard.", CKI_NOTE, 5, CK_EQUIP, 0x0587A15, 0x04 },
    { "c9_map",      "Dungeon Map",         "Shadow Temple.", "Shadow Temple.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A1F, 0x04 },
    { "c9_compass",  "Compass",             "Shadow Temple.", "Shadow Temple.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A1F, 0x02 },
    { "c9_bosskey",  "Boss Key",            "Shadow Temple.", "Shadow Temple.", CKI_SPRITE, 0x10A, CK_EQUIP, 0x0587A1F, 0x01 },
    { "c9_hoverboots","Hover Boots",        "Found in a chest across the invisible bridge over the pit of skulls.", "Shadow Temple.", CKI_SPRITE, 0x110, CK_EQUIP, 0x0587A0F, 0x40 },
    { "c9_gs1",      "Gold Skulltula 1",    "In the spike-trap corridor; use the Lens of Truth to spot it.", "Shadow Temple.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c9_heart",    "Heart Piece",         "In a chest along the spike-trap corridor, reachable with the Hover Boots.", "Shadow Temple.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c9_hc",       "Heart Container",     "Defeat Bongo Bongo.", "Shadow Temple - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A14, 0x10 },
    { "c9_medal",    "Shadow Medallion",    "Given automatically once Bongo Bongo falls.", "Shadow Temple - boss room.", CKI_SPRITE, 0x116, CK_EQUIP, 0x0587A14, 0x10 },
};
static const ChkItem CK_C10[] = { // Spirit Temple
    { "c10_requiem", "Song: Requiem of Spirit", "Taught by Sheik as you first arrive at the Desert Colossus.", "Desert Colossus.", CKI_NOTE, 4, CK_EQUIP, 0x0587A15, 0x02 },
    { "c10_map",     "Dungeon Map",         "Spirit Temple.", "Spirit Temple.", CKI_SPRITE, 0x108, CK_EQUIP, 0x0587A1E, 0x04 },
    { "c10_compass", "Compass",             "Spirit Temple.", "Spirit Temple.", CKI_SPRITE, 0x109, CK_EQUIP, 0x0587A1E, 0x02 },
    { "c10_bosskey", "Boss Key",            "Spirit Temple.", "Spirit Temple.", CKI_SPRITE, 0x10A, CK_EQUIP, 0x0587A1E, 0x01 },
    { "c10_gauntlets","Silver Gauntlets",   "Found in the hand statue's chest after solving the child/adult puzzles.", "Spirit Temple.", CKI_SPRITE, 0x10E, CK_UPGRADE, 0x0587A10, (6 << 3) | 2 },
    { "c10_mirror",  "Mirror Shield",       "Found in a chest guarded by Beamos and Anubis statues.", "Spirit Temple.", CKI_SPRITE, 0x40, CK_EQUIP, 0x0587A0E, 0x40 },
    { "c10_gs1",     "Gold Skulltula 1",    "In the sun-block puzzle room, reflect sunlight to open a locked door.", "Spirit Temple.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c10_heart",   "Heart Piece",         "In the sun-block puzzle room, behind the door opened by the reflected beam.", "Spirit Temple.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c10_hc",      "Heart Container",     "Defeat Twinrova.", "Spirit Temple - boss room.", CKI_SPRITE, 0x102, CK_EQUIP, 0x0587A14, 0x08 },
    { "c10_medal",   "Spirit Medallion",    "Given automatically once Twinrova falls.", "Spirit Temple - boss room.", CKI_SPRITE, 0x115, CK_EQUIP, 0x0587A14, 0x08 },
};
static const ChkItem CK_C11[] = { // Gerudo's Fortress & Haunted Wasteland
    { "c11_carpenters","Rescue the Carpenters", "Sneak through the fortress and free all four captured carpenters from their cells.", "Gerudo's Fortress.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c11_card",    "Gerudo's Membership Card", "Aveil gives it to you once all four carpenters are freed.", "Gerudo's Fortress.", CKI_SPRITE, 0x112, CK_MANUAL, 0, 0 },
    { "c11_archery", "Horseback Archery: 1000 pts", "Score 1000 or more points at the archery range to win a Heart Piece.", "Gerudo's Fortress - archery range.", CKI_SPRITE, 0x103, CK_MANUAL, 0, 0 },
    { "c11_gs1",     "Gold Skulltula 1",    "On the far target at the Horseback Archery range, at night.", "Gerudo's Fortress - archery range.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c11_wasteland","Cross the Haunted Wasteland", "Follow the guiding Poe (or the landmarks) through the quicksand to reach the far side.", "Haunted Wasteland.", CKI_KEYITEM, 0, CK_EQUIP, 0x0587A14, 0x08 },
    { "c11_colossus","Reach the Desert Colossus", "Push through the sandstorm at the end of the wasteland.", "Desert Colossus.", CKI_KEYITEM, 0, CK_EQUIP, 0x0587A14, 0x08 },
};
static const ChkItem CK_C12[] = { // Fishing & Fairies
    { "c12_trade",   "Trade Sequence: Complete", "Carry the chain of trade items from the Goron all the way to Biggoron.", "Death Mountain Trail - Biggoron.", CKI_SPRITE, 0x7C, CK_INVSLOT, 0x05879FA, 0x37 },
    { "c12_biggoron","Biggoron's Sword",    "Biggoron forges it for you once the trade sequence is complete.", "Death Mountain Trail - Biggoron.", CKI_SPRITE, 0x7C, CK_EQUIP, 0x0587A0E, 0x04 },
    { "c12_fishchild","Fishing Pond Record (Child)", "Land the biggest fish you can as child Link.", "Lake Hylia - Fishing Pond.", CKI_SPRITE, 0x19, CK_MANUAL, 0, 0 },
    { "c12_fishadult","Fishing Pond Record (Adult)", "Land the biggest fish you can as adult Link.", "Lake Hylia - Fishing Pond.", CKI_SPRITE, 0x19, CK_MANUAL, 0, 0 },
    { "c12_cow",     "Cow Reward",          "Play Epona's Song in a barn, or claim the free cow from the House of Skulltula.", "Lon Lon Ranch / Kakariko Village.", CKI_SPRITE, 0x1A, CK_MANUAL, 0, 0 },
    { "c12_magic",   "Magic Meter",         "Play Zelda's Lullaby for the Great Fairy inside Death Mountain to receive your first Magic Meter.", "Death Mountain Trail - Great Fairy Fountain.", CKI_SPRITE, 0x104, CK_EQUIP, 0x05879A6, 0xFF },
    { "c12_defense", "Double Defense",      "Lift the boulder with the Golden Gauntlets to reach the Great Fairy outside Ganon's Castle.", "Ganon's Castle - exterior.", CKI_SPRITE, 0x102, CK_EQUIP, 0x05879AA, 0x01 },
};
static const ChkItem CK_C13[] = { // Ganon's Castle
    { "c13_trials",  "Clear the Six Trials","Fight through the Forest, Fire, Water, Shadow, Spirit and Light Trials to reach the tower.", "Ganon's Castle.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c13_gs1",     "Gold Skulltula",      "Hanging from the ceiling in the middle of the Light Trial room.", "Ganon's Castle - Light Trial.", CKI_SPRITE, 0x106, CK_MANUAL, 0, 0 },
    { "c13_tower",   "Climb Ganon's Tower", "Race up the collapsing tower after the trials are cleared.", "Ganon's Castle - tower.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c13_ganondorf","Defeat Ganondorf",   "Use Light Arrows and the Master Sword to bring him down.", "Ganon's Castle - tower top.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
    { "c13_ganon",   "Defeat Ganon",        "The final battle as the castle collapses around you.", "Outside the crumbling tower.", CKI_KEYITEM, 0, CK_MANUAL, 0, 0 },
};
static const ChkCat CHK_CATS[] = {
    { "Kokiri & Deku Tree",                     CK_C0,  (int)(sizeof(CK_C0)  / sizeof(CK_C0[0])) },
    { "Castle & Kakariko",                      CK_C1,  (int)(sizeof(CK_C1)  / sizeof(CK_C1[0])) },
    { "Zora's Domain & Jabu's Belly",           CK_C2,  (int)(sizeof(CK_C2)  / sizeof(CK_C2[0])) },
    { "Death Mountain",                         CK_C3,  (int)(sizeof(CK_C3)  / sizeof(CK_C3[0])) },
    { "Lake Hylia & Gerudo",                    CK_C4,  (int)(sizeof(CK_C4)  / sizeof(CK_C4[0])) },
    { "Becoming an Adult",                      CK_C5,  (int)(sizeof(CK_C5)  / sizeof(CK_C5[0])) },
    { "Forest Temple",                          CK_C6,  (int)(sizeof(CK_C6)  / sizeof(CK_C6[0])) },
    { "Fire Temple",                            CK_C7,  (int)(sizeof(CK_C7)  / sizeof(CK_C7[0])) },
    { "Water Temple",                           CK_C8,  (int)(sizeof(CK_C8)  / sizeof(CK_C8[0])) },
    { "Shadow Temple",                          CK_C9,  (int)(sizeof(CK_C9)  / sizeof(CK_C9[0])) },
    { "Spirit Temple",                          CK_C10, (int)(sizeof(CK_C10) / sizeof(CK_C10[0])) },
    { "Gerudo's Fortress",                      CK_C11, (int)(sizeof(CK_C11) / sizeof(CK_C11[0])) },
    { "Fishing & Fairies",                      CK_C12, (int)(sizeof(CK_C12) / sizeof(CK_C12[0])) },
    { "Ganon's Castle",                         CK_C13, (int)(sizeof(CK_C13) / sizeof(CK_C13[0])) },
};
#define CHK_NCATS  ((int)(sizeof(CHK_CATS) / sizeof(CHK_CATS[0])))
